// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_addnewdoctor.cpp"
#include "EWIEGA46WW/moc_addnewicu.cpp"
#include "EWIEGA46WW/moc_addnewpatient.cpp"
#include "EWIEGA46WW/moc_addnewprescription.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
